//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication7.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort.
        /// </summary>
        internal static string Comfort {
            get {
                return ResourceManager.GetString("Comfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats, extras, ....
        /// </summary>
        internal static string ComfortDefinition {
            get {
                return ResourceManager.GetString("ComfortDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs.
        /// </summary>
        internal static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating costs are the expenses which are related to the operation of the vehicle. It is the regular, usual and customary recurring costs. This does not include the capital cost of constructing or purchasing the vehicle..
        /// </summary>
        internal static string CostsDefinition {
            get {
                return ResourceManager.GetString("CostsDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectable numbers between 1-10: The higher the better..
        /// </summary>
        internal static string DescriptionOfTheDecimalRatingValues {
            get {
                return ResourceManager.GetString("DescriptionOfTheDecimalRatingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance when bought.
        /// </summary>
        internal static string DistanceWhenBought {
            get {
                return ResourceManager.GetString("DistanceWhenBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driven distance.
        /// </summary>
        internal static string DrivenDistance {
            get {
                return ResourceManager.GetString("DrivenDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        internal static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality, speed, relyability of the garage&apos;s service.
        /// </summary>
        internal static string GarageDefinition {
            get {
                return ResourceManager.GetString("GarageDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed, acceleration, breaks, ....
        /// </summary>
        internal static string PerformanceDefinition {
            get {
                return ResourceManager.GetString("PerformanceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        internal static string Reliability {
            get {
                return ResourceManager.GetString("Reliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represent the ability of the wheicle to function under regular conditions.
        /// </summary>
        internal static string RelyabilityDefinition {
            get {
                return ResourceManager.GetString("RelyabilityDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your car, current or former....
        /// </summary>
        internal static string ReviewForm_Welcome {
            get {
                return ResourceManager.GetString("ReviewForm_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Rating.
        /// </summary>
        internal static string SubmitRating {
            get {
                return ResourceManager.GetString("SubmitRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of manufacture.
        /// </summary>
        internal static string YearOfManufacture {
            get {
                return ResourceManager.GetString("YearOfManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of purchase.
        /// </summary>
        internal static string YearOfPurchase {
            get {
                return ResourceManager.GetString("YearOfPurchase", resourceCulture);
            }
        }
    }
}
